service: maintenance-tasks
runtime: python27
threadsafe: True
api_version: 1

instance_class: B4
basic_scaling:
  max_instances: 20
  idle_timeout: 3m

libraries:
- name: grpcio
  version: "1.0.0"
- name: setuptools
  version: "36.6.0"
  
handlers:
- url: /.*
  script: main.app
  login: admin
